CREATE TABLE `algorithm_config` (
	`id` int AUTO_INCREMENT NOT NULL,
	`rsiUpper` int NOT NULL DEFAULT 70,
	`rsiLower` int NOT NULL DEFAULT 30,
	`stopLossPercent` decimal(5,2) NOT NULL DEFAULT '1.5',
	`largeVolumeThreshold` int NOT NULL DEFAULT 8000,
	`recentWinRate` decimal(10,6) NOT NULL DEFAULT '0',
	`recentProfitRate` decimal(10,6) NOT NULL DEFAULT '0',
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `algorithm_config_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `algorithm_improvements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dailyReportId` int NOT NULL,
	`prevRsiUpper` int NOT NULL,
	`prevRsiLower` int NOT NULL,
	`prevStopLossPercent` decimal(5,2) NOT NULL,
	`newRsiUpper` int NOT NULL,
	`newRsiLower` int NOT NULL,
	`newStopLossPercent` decimal(5,2) NOT NULL,
	`improvementReason` text NOT NULL,
	`appliedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `algorithm_improvements_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `daily_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`reportDate` varchar(10) NOT NULL,
	`totalInitialCapital` bigint NOT NULL,
	`totalFinalBalance` bigint NOT NULL,
	`totalProfitAmount` bigint NOT NULL,
	`totalProfitRate` decimal(10,6) NOT NULL,
	`totalWinCount` int NOT NULL DEFAULT 0,
	`totalLossCount` int NOT NULL DEFAULT 0,
	`overallWinRate` decimal(10,6) NOT NULL DEFAULT '0',
	`rsiUpper` int NOT NULL DEFAULT 70,
	`rsiLower` int NOT NULL DEFAULT 30,
	`stopLossPercent` decimal(5,2) NOT NULL DEFAULT '1.5',
	`aiSummary` text,
	`isAutoGenerated` boolean NOT NULL DEFAULT false,
	`scheduleCronTaskUid` varchar(65),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `daily_reports_id` PRIMARY KEY(`id`),
	CONSTRAINT `daily_reports_reportDate_unique` UNIQUE(`reportDate`)
);
--> statement-breakpoint
CREATE TABLE `stock_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dailyReportId` int NOT NULL,
	`symbol` varchar(10) NOT NULL,
	`name` varchar(50) NOT NULL,
	`initialCapital` bigint NOT NULL,
	`finalBalance` bigint NOT NULL,
	`profitAmount` bigint NOT NULL,
	`profitRate` decimal(10,6) NOT NULL,
	`tradesCount` int NOT NULL DEFAULT 0,
	`winCount` int NOT NULL DEFAULT 0,
	`winRate` decimal(10,6) NOT NULL DEFAULT '0',
	`trades` json NOT NULL,
	`lossCauses` json NOT NULL,
	`countermeasures` json NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `stock_reports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openId` varchar(64) NOT NULL,
	`name` text,
	`email` varchar(320),
	`loginMethod` varchar(64),
	`role` enum('user','admin') NOT NULL DEFAULT 'user',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastSignedIn` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_openId_unique` UNIQUE(`openId`)
);
